# JMeter Test Execution Dockerfile
# Generated by JMeter MCP Server

FROM justb4/jmeter:latest

# Set working directory
WORKDIR /jmeter

# Create directories for results
RUN mkdir -p /tests /data /results/reports /results/logs

# Copy execution script
COPY docker-entrypoint.sh /entrypoint.sh

# Make script executable
RUN chmod +x /entrypoint.sh

ENTRYPOINT ["/entrypoint.sh"]
