#!/bin/bash
# JMeter Test Execution Script
# Generated by JMeter MCP Server

set -e

TEST_NAME="Basic_UI_Login_Test"
JMX_FILE="Basic_UI_Login_Test.jmx"
TIMESTAMP=$(date +"%Y%m%d-%H%M%S")

echo "🐳 JMeter Docker Test Execution"
echo "================================"
echo "Test: $TEST_NAME"
echo "File: $JMX_FILE"
echo "Time: $TIMESTAMP"
echo ""

# Check prerequisites
echo "🔍 Checking prerequisites..."
if ! command -v docker &> /dev/null; then
    echo "❌ Docker is not installed or not in PATH"
    exit 1
fi

if ! docker info &> /dev/null; then
    echo "❌ Docker is not running"
    exit 1
fi

if [ ! -f "output/$JMX_FILE" ]; then
    echo "❌ JMX file not found: output/$JMX_FILE"
    exit 1
fi

echo "✅ Prerequisites check passed"
echo ""

# Clean up previous results
echo "🧹 Cleaning up previous results..."
rm -rf jmeter-results/*
mkdir -p jmeter-results

# Build and run with Docker Compose
echo "🚀 Starting test execution with Docker Compose..."
docker-compose up --build --remove-orphans

echo ""
echo "✅ Test execution completed!"
echo "📊 Results available in: ./jmeter-results/"
echo "🌐 Open ./jmeter-results/reports/index.html for dashboard"

# Optional: Open results in browser (uncomment for auto-open)
# if command -v xdg-open &> /dev/null; then
#     xdg-open "./jmeter-results/reports/index.html"
# elif command -v open &> /dev/null; then
#     open "./jmeter-results/reports/index.html"
# fi

echo "🎉 Execution script completed successfully!"
